/* Generated by portfolio.plugin.ts from public/portfolio/ at build time. */
declare module "virtual:portfolio" {
  export type PortfolioFile = {
    path: string;
    mime: string;
    size: number;
    modified: number;
    url?: string;
    content?: string;
  };
  export const files: PortfolioFile[];
}
